# Generated by Django 3.0.5 on 2020-05-04 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=999)),
                ('price', models.IntegerField()),
                ('release_date', models.DateField()),
                ('shop_arrival_date', models.DateField(blank=True, default=datetime.date.today)),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Manufacturer')),
            ],
        ),
    ]
