# Generated by Django 3.0.5 on 2020-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
