# Generated by Django 3.0.5 on 2020-05-09 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_arrival_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
