# Generated by Django 3.0.5 on 2020-05-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200509_1344'),
        ('product', '0002_auto_20200509_1643'),
    ]

    operations = [
    ]
