# Generated by Django 3.0.5 on 2020-05-12 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_merge_20200509_1805'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
