# Generated by Django 3.0.5 on 2020-05-10 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_merge_20200509_1805'),
        ('user', '0002_auto_20200509_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/nav_img/default_profile_image.svg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='search',
            name='date_of_search',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='search',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(to='product.Product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Profile')),
            ],
        ),
    ]
