# Generated by Django 3.0.5 on 2020-05-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200510_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/profile/default_profile_image.svg', upload_to='images/profile/'),
        ),
    ]
